# Generated by Django 4.2.8 on 2024-01-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(related_name='bookings', to='hotel.room'),
        ),
    ]
