# Generated by Django 4.2.8 on 2024-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('booking', '0002_alter_booking_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(to='hotel.room'),
        ),
    ]
