# Generated by Django 4.2.8 on 2024-01-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
